name: test

on:
  push:
    branches:
    - master
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Determine version number
      id: version
      shell: bash
      run: |
        if [ "${{ vars.BASE_VERSION_NUMBER }}" != '' ]; then
          echo "value=$(${{ vars.BASE_VERSION_NUMBER }} + ${{ github.run_number }})" >> $GITHUB_OUTPUT;
        else
          echo "value=${{ github.run_number }}" >> $GITHUB_OUTPUT;
        fi

    - name: Environment variables to output 
      id: init
      run: echo "version=${{ steps.version.outputs.value }}" >> $GITHUB_OUTPUT
